name: Java CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: check dir estructure
        run: |
          pwd
          ls -latR
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Create target dir
        run: mkdir staging && cp target/*.jar staging
      - name: check dir estructure
        run: |
          pwd
          ls -latR
      - name: Create artifac
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          
      